services:
  - rabbitmq

language: php

php:
  - 5.5
  - 5.6

install:
  - pecl install -f amqp
  - composer self-update

before_script:
  - composer install --no-interaction

script:
  - phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
