sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services:
  - rabbitmq

language: php

php:
  - 5.5
  - 5.6
  # - 7.0  enable when amqp extension is available
  # - hhvm enable when amqp extension is available

matrix:
  fast_finish: true

install:
  - pecl install -f amqp

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [[ $TRAVIS_PHP_VERSION == '5.6' ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
